
export const NIFTY_50_STOCKS = [
  { symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Energy', basePrice: 1290.50 },
  { symbol: 'TCS', name: 'Tata Consultancy Svc', sector: 'IT', basePrice: 4150.20 },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Financial Services', basePrice: 1740.00 },
  { symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Financial Services', basePrice: 1260.45 },
  { symbol: 'INFY', name: 'Infosys', sector: 'IT', basePrice: 1880.30 },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'Consumer Goods', basePrice: 2790.00 },
  { symbol: 'ITC', name: 'ITC Ltd', sector: 'Consumer Goods', basePrice: 485.60 },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Financial Services', basePrice: 815.20 },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecom', basePrice: 1640.75 },
  { symbol: 'LICI', name: 'LIC India', sector: 'Financial Services', basePrice: 1025.00 },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Financial Services', basePrice: 1790.50 },
  { symbol: 'LT', name: 'Larsen & Toubro', sector: 'Construction', basePrice: 3550.00 },
  { symbol: 'HCLTECH', name: 'HCL Technologies', sector: 'IT', basePrice: 1780.25 },
  { symbol: 'ASIANPAINT', name: 'Asian Paints', sector: 'Consumer Goods', basePrice: 2850.00 },
  { symbol: 'AXISBANK', name: 'Axis Bank', sector: 'Financial Services', basePrice: 1180.60 },
  { symbol: 'MARUTI', name: 'Maruti Suzuki', sector: 'Automobile', basePrice: 12400.00 },
  { symbol: 'SUNPHARMA', name: 'Sun Pharma', sector: 'Pharma', basePrice: 1790.00 },
  { symbol: 'TITAN', name: 'Titan Company', sector: 'Consumer Goods', basePrice: 3350.00 },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', sector: 'Financial Services', basePrice: 6950.00 },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', sector: 'Construction', basePrice: 11200.00 },
  { symbol: 'ONGC', name: 'ONGC', sector: 'Energy', basePrice: 295.40 },
  { symbol: 'NTPC', name: 'NTPC', sector: 'Energy', basePrice: 410.15 },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', sector: 'Automobile', basePrice: 945.50 },
  { symbol: 'POWERGRID', name: 'Power Grid Corp', sector: 'Energy', basePrice: 330.25 },
  { symbol: 'JSWSTEEL', name: 'JSW Steel', sector: 'Metals', basePrice: 960.00 },
  { symbol: 'TATASTEEL', name: 'Tata Steel', sector: 'Metals', basePrice: 148.50 },
  { symbol: 'M&M', name: 'Mahindra & Mahindra', sector: 'Automobile', basePrice: 2880.00 },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', sector: 'Metals', basePrice: 2950.00 },
  { symbol: 'ADANIPORTS', name: 'Adani Ports', sector: 'Infrastructure', basePrice: 1380.00 },
  { symbol: 'COALINDIA', name: 'Coal India', sector: 'Metals', basePrice: 490.50 },
  { symbol: 'WIPRO', name: 'Wipro', sector: 'IT', basePrice: 545.00 },
  { symbol: 'BPCL', name: 'BPCL', sector: 'Energy', basePrice: 345.20 },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', sector: 'Financial Services', basePrice: 1620.00 },
  { symbol: 'GRASIM', name: 'Grasim Industries', sector: 'Construction', basePrice: 2650.00 },
  { symbol: 'CIPLA', name: 'Cipla', sector: 'Pharma', basePrice: 1540.00 },
  { symbol: 'TECHM', name: 'Tech Mahindra', sector: 'IT', basePrice: 1620.00 },
  { symbol: 'HINDALCO', name: 'Hindalco', sector: 'Metals', basePrice: 680.50 },
  { symbol: 'DRREDDY', name: 'Dr Reddys Labs', sector: 'Pharma', basePrice: 6450.00 },
  { symbol: 'BRITANNIA', name: 'Britannia', sector: 'Consumer Goods', basePrice: 5850.00 },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance', sector: 'Financial Services', basePrice: 1720.00 },
  { symbol: 'EICHERMOT', name: 'Eicher Motors', sector: 'Automobile', basePrice: 4750.00 },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank', sector: 'Financial Services', basePrice: 1380.00 },
  { symbol: 'DIVISLAB', name: 'Divis Labs', sector: 'Pharma', basePrice: 5600.00 },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', sector: 'Pharma', basePrice: 6900.00 },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto', sector: 'Automobile', basePrice: 9850.00 },
  { symbol: 'TATACONSUM', name: 'Tata Consumer', sector: 'Consumer Goods', basePrice: 1120.00 },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', sector: 'Automobile', basePrice: 5450.00 },
  { symbol: 'UPL', name: 'UPL', sector: 'Chemicals', basePrice: 560.00 },
];
